### ISSUE TITLE
C:WHEN doesn't work inside an iteration

### ISSUE THREAD

**Issue by gingeralesy** [Shinmera/clip#3]
`(clip:process "<a iterate=\"a\"><c:when test=\"T\">b" :a '(1 2 3))`
Errors with `The value of ARRAY-UTILS::FROM is NIL, which is not of type ARRAY-UTILS::POSITIVE-FIXNUM.` which happens during tag processing of the C:WHEN element.

Expected result in above example would be getting three `b`s inside the `a` element. Right now it errors.

Confirmed to happen on the latest master branch.

**Comment by Shinmera** [comment]
This should have been fixed since.
